# Generated by Django 6.1.1 on 2026-09-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engineering', '0002_cleanproduct'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rawdatarecord',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_external_id'),
        ),
    ]
