# Generated by Django 6.1.1 on 2026-09-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engineering', '0003_rawdatarecord_unique_source_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
