# Generated by Django 6.1.1 on 2026-09-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engineering', '0005_dataqualityissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanproduct',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='cleanproduct',
            constraint=models.UniqueConstraint(fields=('source', 'product_id'), name='unique_source_product'),
        ),
    ]
