# Generated by Django 6.1.1 on 2026-09-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engineering', '0006_alter_cleanproduct_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cleanproduct',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cleanproduct',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='cleanproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cleanproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
