# Generated by Django 6.1.1 on 2026-09-23 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engineering', '0007_cleanproduct_brand_cleanproduct_discount_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('stock', models.IntegerField(default=0)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='data_engineering.cleanproduct')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['product', 'captured_at'], name='data_engine_product_9d1225_idx'), models.Index(fields=['captured_at'], name='data_engine_capture_9eef63_idx')],
            },
        ),
    ]
