# Generated by Django 6.1.1 on 2026-09-23 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engineering', '0008_productsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsnapshot',
            name='pipeline_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='data_engineering.pipelinerun'),
        ),
        migrations.AddIndex(
            model_name='productsnapshot',
            index=models.Index(fields=['pipeline_run'], name='data_engine_pipelin_e189fb_idx'),
        ),
    ]
