# Generated by Django 6.1.1 on 2026-09-24 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engineering', '0009_productsnapshot_pipeline_run_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_stock', models.FloatField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('actual_stock', models.FloatField(blank=True, null=True)),
                ('prediction_error', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='data_engineering.cleanproduct')),
            ],
            options={
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['product', '-predicted_at'], name='data_engine_product_38641b_idx'), models.Index(fields=['status'], name='data_engine_status_c96b8e_idx')],
            },
        ),
    ]
